### ISSUE TITLE
Critical error - new gravity forms entry

### ISSUE THREAD

**Issue by andrebalza** [omgwtfwow/segment-for-wp-by-in8-io#2]
Hello Juan, 
this showed up when the user submitted a gravity forms entry.
The relevant  settings: Track Gravity forms: ON, Track server side: ON, Identify: ON
Thanks again for this greatly  useful plugin.
Frontend:
>There has been a critical error on this website.

Error log:
2021/10/06 06:45:55 [error] 47638#47638: *20903 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Error saving action: ActionScheduler_Action::$args too long. To ensure the args column can be indexed, action args should not be more than 8000 characters when encoded as JSON. in /var/www/website.com/htdocs/wp-content/plugins/segment-for-wp-by-in8-io/includes/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:86
Stack trace:
#0 /var/www/website.com/htdocs/wp-content/plugins/segment-for-wp-by-in8-io/includes/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_DBStore->save_action(Object(ActionScheduler_Action))
#1 /var/www/website.com/htdocs/wp-content/plugins/segment-for-wp-by-in8-io/includes/action-scheduler/classes/ActionScheduler_ActionFactory.php(69): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action))
#2 /var/www/website.com/htdocs/wp-content/plugins/segment-for-wp-by-in8-io/includes/action-scheduler/functions.php(19): ActionScheduler_ActionFactory->async('async_task', Ar" while reading response header from upstream, client: 192.89.29.225, server: website.com, request: "POST /my-dashboard/article/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php73-two-fpm.sock:", host: "website.com", referrer: "https://website.com/my-dashboard/article/"

**Comment by andrebalza** [comment]
The form in question has 33 fields, plus add-ons are active on it (if it matters)
I just noticed that the error kicks in even if the 'Track Gravity forms' is switched off.
Thank you Juan
